

/**
 * Class: Main_Form
 * Description: The very first window that the user sees for the program.
 *      gives a starting point to access all other forms such as the history form
 *      or the expense form. Also provides option of quitting or seeking help.
 * @author Ray, Kim, Trevor
 * Date Created: Oct. 2, 2016
 * History:
 */
public class Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form Main_Form
     */
    public Main_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mula");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameJLabel = new javax.swing.JLabel();
        buttonJPanel = new javax.swing.JPanel();
        expenseJButton = new javax.swing.JButton();
        historyJButton = new javax.swing.JButton();
        helpJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        helpJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameJLabel.setText("jLabel1");

        buttonJPanel.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        expenseJButton.setFont(new java.awt.Font("Shree Devanagari 714", 1, 18)); // NOI18N
        expenseJButton.setText("Expenses");
        expenseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseJButtonActionPerformed(evt);
            }
        });
        buttonJPanel.add(expenseJButton);

        historyJButton.setFont(new java.awt.Font("Shree Devanagari 714", 1, 18)); // NOI18N
        historyJButton.setText("History");
        historyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyJButtonActionPerformed(evt);
            }
        });
        buttonJPanel.add(historyJButton);

        helpJButton.setFont(new java.awt.Font("Shree Devanagari 714", 1, 18)); // NOI18N
        helpJButton.setText("Help");
        helpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJButtonActionPerformed(evt);
            }
        });
        buttonJPanel.add(helpJButton);

        quitJButton.setFont(new java.awt.Font("Shree Devanagari 714", 1, 18)); // NOI18N
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        buttonJPanel.add(quitJButton);

        jMenu1.setText("About");

        helpJMenuItem.setText("Help");
        helpJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(helpJMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(buttonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(buttonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * Method: quitJButtonActionPerformed
     * Description: Disposes the current form.
     * @param evt 
     * Author: Ray, Kim, Trevor
     * History:
     */
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    
    
    /**
     * Method: helpJButtonActionPerformed
     * Description: A Button event that creates and displays a dialog form
     *      that shows information concerning the application.
     * @param evt 
     * Author: Trevor
     * Date Created: Oct. 11, 2016
     * History:
     */
    private void helpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJButtonActionPerformed
        //create a Dialog form that has shows documentation.
        
        helpJDialog helpForm = new helpJDialog(this,true);
        
        helpForm.setVisible(true);
        
    }//GEN-LAST:event_helpJButtonActionPerformed

    
    
    private void historyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyJButtonActionPerformed
        // create a form for history
    }//GEN-LAST:event_historyJButtonActionPerformed

    
    
    /**
     * Method: expenseJButtonActionPerformed
     * Description: Creates and shows a new form meant to allow user to input 
     *      and save data concerning their expenses. Makes the current form 
     *      invisible as well.
     * @param evt 
     * Author: Ray, Kim,  Trevor
     * Date Created: Oct. 2, 2016
     * History: Oct. 11, 2016 Trevor - Set the visibility of the current form to false
     *          instead of disposing it.
     */
    private void expenseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseJButtonActionPerformed
        // TODO add your handling code here:
        expense_form expenses = new expense_form();
        expenses.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_expenseJButtonActionPerformed

    
    /**
     * Method: helpJMenuItemActionPerformed
     * Description: An action event that invokes the click event of the 
     *          helpJButton.
     * @param evt 
     * Date Created: Oct 11, 2016
     * History:
     */
    private void helpJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJMenuItemActionPerformed
        // TODO add your handling code here:
        helpJButton.doClick();
    }//GEN-LAST:event_helpJMenuItemActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonJPanel;
    private javax.swing.JButton expenseJButton;
    private javax.swing.JButton helpJButton;
    private javax.swing.JMenuItem helpJMenuItem;
    private javax.swing.JButton historyJButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel usernameJLabel;
    // End of variables declaration//GEN-END:variables
}
